### PR TITLE
Fix invalid date issue && Add new style

### PR DESCRIPTION
**Pull request by Allianzcortex**
Ticket : 

---

Description : 

What has been done : 

1. update style && fix invalid date issue : 

currently it will show `Invalid Date` sometimes like the following(e.g. choose type to I-360 to reproduce it)

image

now it will show `date does not exist` in this branch : 

image

2. change formgroup selector from `column` to `row` for a better user experience

image

### CODE REVIEW

**Comment by Allianzcortex** [comment]
@vicdus PTAL when u have time ? ^^

**Comment by Allianzcortex** [comment]
@vicdus So I see this the issue has been fixed in another way , whats ur ideas about the style changes ?  If you have another design-refactor roadmap I will close this PR for now.

**Comment by vicdus** [comment]
thanks!!

**Comment by Allianzcortex** [comment]
BTW @vicdus  do u consider adding a GitHub action for it so the data can be updated daily automatically?  if so I can push a PR for it. it will work as this repo : https://github.com/Allianzcortex/2021/commits/master

**Pull request merged**
